version: '3.8'

services:
  anycrawl-mcp:
    build: .
    container_name: anycrawl-mcp-server
    environment:
      - ANYCRAWL_API_KEY=${ANYCRAWL_API_KEY}
      - ANYCRAWL_BASE_URL=${ANYCRAWL_BASE_URL:-https://api.anycrawl.dev}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - anycrawl-network

networks:
  anycrawl-network:
    driver: bridge
