version: '3.8'

services:
  anycrawl-mcp-combined:
    build:
      context: .
      dockerfile: Dockerfile.combined
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - ANYCRAWL_MODE=COMBINED
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/health']
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
